### ISSUE TITLE
Add images for index placeholders

### ISSUE THREAD

**Issue by justincampbell** [justincampbell/wedding#17]

**Comment by justincampbell** [comment]
Done in fdc8eee

**Comment by justincampbell** [comment]
@aharris This needs some CSS lovin'

**Comment by justincampbell** [comment]
@bkemeny What do you think of the pics here: fdc8eee ?

**Comment by bkemeny** [comment]
I didn't notice a different between the two emails of images. Both were a
group of pics but I like them!

Sent from my iPhone

On Oct 11, 2012, at 2:14 AM, Justin Campbell notifications@github.com
wrote:

@bkemeny https://github.com/bkemeny What do you think of the pics here:
fdc8eee https://github.com/JustinCampbell/wedding/commit/fdc8eee ?

—
Reply to this email directly or view it on
GitHubhttps://github.com/JustinCampbell/wedding/issues/17#issuecomment-9329633.
