### ISSUE TITLE
Add venue/hotel/travel copy

### ISSUE THREAD

**Issue by justincampbell** [justincampbell/wedding#25]

**Comment by bkemeny** [comment]
Venue:
Merion Tribute House
http://tributehouse.com/index.asp

Map of Location
http://tributehouse.com/directions.asp 

Directions
Merion Tribute House
625 Hazelhurst Avenue, Merion Station, PA 19066
From theSchuylkill Expressway
Schuylkill Expressway (76) to City Ave. Exit 339 (Route 1 South), continue South on City Avenue 2.5 miles to E. Wynnewood Rd. Turn right on E. Wynnewood Rd., follow 0.5 miles (6 blocks) to Hazelhurst Ave. Turn right on Hazelhurst Ave., go 3.5 blocks. The Merion Tribute House will be on your left. Two lots in the rear provide ample parking for over 120 cars.
From South Jersey
Cross over Benjamin Franklin Bridge, take 676 (Vine St. Expressway) to 76 West. Exit at City Avenue (Exit 339) and follow directions listed above.
From New York
NJ Turnpike S to Exit 6 of PA Turnpike. Follow PA Turnpike and get off at Mid County Exit 20 (Rt. 476). Take Rt 476 to Exit 16 (a short distance) to Rt. 76 East towards Philadelphia. Exit at City Avenue (Exit 339) and follow directions listed above.
Public Transportation
The Merion Tribute House is also within walking distance of the Merion Station on SEPTA's R-5 line.

History
How we began...

Immediately after World War I, there was interest among Merion residents in creating a community center with facilities for cultural and social events as well as a playground for children. Elridge Johnson, founder in 1891 of the Victor Talking Machine Company in Camden, offered to demolish the house on his property and build a "Tribute House" in recognition of the 81 men from Merion who were in the armed services. 
About our building...

Mr. Johnson requested that the building be "the most beautiful structure of its kind in this locality." Karcher and Smith, Architects, were selected to design the building using Gothic patterns and local stone. The arts and crafts tradition of the early 20th century promoted attention to detail throughout the construction. The stone was shaped on site and the window mullions all handcut to match. The ornamental iron work and lamps were designed by Samuel Yellin craftsmen. There are military emblems embedded in stained glass, hand carved decorative figures and division patches awaiting discovery by guests.

Travel
Traveling from far away? Or maybe you just want an excuse to stay over?
We have registered a block of rooms at the Hampton Inn in West Chester

Room Rate $89/night
Please Reserve by December 13th to receive this rate by clicking the link below or phone reservations can be made by calling 610-358-9540 or 1-800-HAMPTON and mentioning the Kemeny Campbell Wedding.  
http://hamptoninn.hilton.com/en/hp/groups/personalized/C/CFORDHX-KCB-20121231/index.jhtml?WT.mc_id=POG

Shuttles
There will be two courtesy shuttles leaving from the hotel promptly at 3:30 PM to take hotel guests to the Venue and home at the end of the night. 

Sunday Brunch
If you are staying over, we would love for you to join us for a small casual breakfast on Sunday morning, also in West Chester, PA.  Details will be available soon, please check back or sign up for e-mails when the site is updated. (We promise not to SPAM you!)

Insert email address thing

(If you can’t make it to brunch, while we’d love to see you, the Hampton Inn has a pretty awesome free hot breakfast!)

Things to do:
If we haven’t provided you with enough to keep you busy - 
Check out the city of West Chester http://www.downtownwestchester.com/
Or even drive to downtown Philadelphia for the many historic sites and museums available http://www.visitphilly.com/

**Comment by justincampbell** [comment]
Added most of these things
