### ISSUE TITLE
Add meal descriptions to RSVP page

### ISSUE THREAD

**Issue by justincampbell** [justincampbell/wedding#27]

**Comment by bkemeny** [comment]
Entrees:
Chicken:
    Polo Fromaggio - tastes like a pretty awesome chicken parm without the breading, finished with fontina cheese and sundried tomatoes, complimented with a champagne confetti sauce and accompanied by red bliss garlic smashed potatoes
Steak:
    Grilled Chateaubriand - pretty much your standard filet, with cabernet sauce and sauteed mushrooms (accompanied by red bliss garlic smashed potatoes)
Seafood: 
    Brandied Seafood newburg - a delectable combination of shrimp, scallops, and jumbo lumb crab served over saffron rice
Vegetarian:
    Stuffed Ravioli and Grilled Vegetables - parmesan cheese and basil pasta with  grilled portobello mushrooms, red, green, and yellow peppers.
